# Short           Long
# r               read_data
# w               write_data
# x               execute
# p               append_data
# D               delete_child
# d               delete
# a               read_attributes
# A               write_attributes
# R               read_xattr
# W               write_xattr
# c               read_acl
# C               write_acl
# o               write_owner
# s               synchronize


[series]
path = "/mnt/data/series/incoming"
dir_facl = """
	owner@:rwxpDdaARWcCos:------I:allow
	group@:rwxpDdaARWcCos:------I:allow
    everyone@:r-x---a-R-c---:------I:allow
"""
file_facl = """
    owner@:rwxpDdaARWcCos:------I:allow
	group@:rwxpDdaARWcCos:------I:allow
    everyone@:r-x---a-R-c---:------I:allow
"""

[movies]
path = "/mnt/data/movies/incoming"
dir_facl = """
	owner@:rwxpDdaARWcCos:------I:allow
	group@:rwxpDdaARWcCos:------I:allow
    everyone@:r-x---a-R-c---:------I:allow
"""
file_facl = """
    owner@:rwxpDdaARWcCos:------I:allow
	group@:rwxpDdaARWcCos:------I:allow
    everyone@:r-x---a-R-c---:------I:allow
"""